<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Tool;
use Illuminate\Database\Seeder;

class DefaultToolsSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            [
                'name'                  => 'bash',
                'display_name'          => 'Bash Shell',
                'description'           => 'Execute a shell command with path restrictions enforced.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\BashTool',
                'risk_level'            => 'dangerous',
                'requires_confirmation' => true,
            ],
            [
                'name'                  => 'file_read',
                'display_name'          => 'File Read',
                'description'           => 'Read the contents of a file at an allowed path.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\FileReadTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'file_write',
                'display_name'          => 'File Write',
                'description'           => 'Write or create a file at an allowed path.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\FileWriteTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'file_list',
                'display_name'          => 'File List',
                'description'           => 'List the contents of a directory.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\FileListTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'http_get',
                'display_name'          => 'HTTP GET',
                'description'           => 'Perform an HTTP GET request to a URL.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\HttpGetTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'http_post',
                'display_name'          => 'HTTP POST',
                'description'           => 'Perform an HTTP POST request to a URL with a payload.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\HttpPostTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'memory_read',
                'display_name'          => 'Memory Read',
                'description'           => 'Read entries from the persistent memory store.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\MemoryReadTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'memory_write',
                'display_name'          => 'Memory Write',
                'description'           => 'Write an entry to the persistent memory store.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\MemoryWriteTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'telegram_send',
                'display_name'          => 'Telegram Send',
                'description'           => 'Send a message to the authorized Telegram user.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\TelegramSendTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'skill_read',
                'display_name'          => 'Skill Read',
                'description'           => 'Read the SKILL.md file of an installed skill.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\SkillReadTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'process_status',
                'display_name'          => 'Process Status',
                'description'           => 'Check the status of running processes on the server.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\ProcessStatusTool',
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'laravel_artisan',
                'display_name'          => 'Laravel Artisan',
                'description'           => 'Run a Laravel Artisan command.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\LaravelArtisanTool',
                'risk_level'            => 'dangerous',
                'requires_confirmation' => true,
            ],
            [
                'name'                  => 'git_operation',
                'display_name'          => 'Git Operation',
                'description'           => 'Perform git operations: pull, status, log (no force push).',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\GitOperationTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'composer_operation',
                'display_name'          => 'Composer Operation',
                'description'           => 'Run composer install or update.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\ComposerOperationTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'npm_operation',
                'display_name'          => 'NPM Operation',
                'description'           => 'Run npm install or npm run scripts.',
                'type'                  => 'builtin',
                'handler_class'         => 'App\\Services\\Tools\\NpmOperationTool',
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],

            // ── New useful tools ──────────────────────────────────────────────

            [
                'name'                  => 'web_search',
                'display_name'          => 'Web Search',
                'description'           => 'Search the web via DuckDuckGo Instant Answer API and return results.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'json_api',
                'display_name'          => 'JSON API Call',
                'description'           => 'Make a GET/POST request to a JSON API and return the parsed response.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'file_delete',
                'display_name'          => 'File Delete',
                'description'           => 'Delete a file at an allowed path.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'dangerous',
                'requires_confirmation' => true,
            ],
            [
                'name'                  => 'file_search',
                'display_name'          => 'File Search',
                'description'           => 'Search for files by name or content within allowed paths.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'send_email',
                'display_name'          => 'Send Email',
                'description'           => 'Send an email via the configured SMTP mailer.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => true,
                'config_keys'           => ['MAIL_MAILER', 'MAIL_HOST', 'MAIL_PORT', 'MAIL_USERNAME', 'MAIL_PASSWORD', 'MAIL_FROM_ADDRESS'],
            ],
            [
                'name'                  => 'cron_list',
                'display_name'          => 'Cron List',
                'description'           => 'List all scheduled FlamingDragon tasks (Laravel scheduler).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'db_query',
                'display_name'          => 'DB Query (read-only)',
                'description'           => 'Run a read-only SELECT query on the application database.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'image_generate',
                'display_name'          => 'Image Generate',
                'description'           => 'Generate an image via OpenAI DALL-E 3 and return the URL.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['OPENAI_API_KEY'],
            ],
            [
                'name'                  => 'summarize_url',
                'display_name'          => 'Summarize URL',
                'description'           => 'Fetch a URL and return a concise LLM-generated summary of the content.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'weather',
                'display_name'          => 'Weather',
                'description'           => 'Get current weather for a location using the Open-Meteo free API (no key needed).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],

            // ── Gmail ─────────────────────────────────────────────────────────

            [
                'name'                  => 'gmail_list',
                'display_name'          => 'Gmail — List Messages',
                'description'           => 'List recent or filtered Gmail messages (inbox, unread, etc.).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],
            [
                'name'                  => 'gmail_read',
                'display_name'          => 'Gmail — Read Message',
                'description'           => 'Read the full content of a Gmail message by ID. Marks it as read.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],
            [
                'name'                  => 'gmail_send',
                'display_name'          => 'Gmail — Send Email',
                'description'           => 'Compose and send an email via Gmail (OAuth2).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => true,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],
            [
                'name'                  => 'gmail_search',
                'display_name'          => 'Gmail — Search',
                'description'           => 'Search Gmail using Gmail query syntax (from:, subject:, is:unread, etc.).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],
            [
                'name'                  => 'gmail_mark_read',
                'display_name'          => 'Gmail — Mark as Read',
                'description'           => 'Mark a Gmail message as read by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],
            [
                'name'                  => 'gmail_trash',
                'display_name'          => 'Gmail — Move to Trash',
                'description'           => 'Move a Gmail message to trash by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'dangerous',
                'requires_confirmation' => true,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_GMAIL_REFRESH_TOKEN'],
            ],

            // ── Google Calendar ───────────────────────────────────────────────

            [
                'name'                  => 'google_calendar_list',
                'display_name'          => 'Google Calendar — List Events',
                'description'           => 'List upcoming events from Google Calendar (requires OAuth2 credentials in .env).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN', 'GOOGLE_CALENDAR_ID'],
            ],
            [
                'name'                  => 'google_calendar_create',
                'display_name'          => 'Google Calendar — Create Event',
                'description'           => 'Create a new Google Calendar event.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN', 'GOOGLE_CALENDAR_ID'],
            ],
            [
                'name'                  => 'google_calendar_delete',
                'display_name'          => 'Google Calendar — Delete Event',
                'description'           => 'Delete a Google Calendar event by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'dangerous',
                'requires_confirmation' => true,
                'config_keys'           => ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REFRESH_TOKEN', 'GOOGLE_CALENDAR_ID'],
            ],

            // ── Todos ─────────────────────────────────────────────────────────

            [
                'name'                  => 'todo_create',
                'display_name'          => 'Todo — Create',
                'description'           => 'Create a new todo item in a named list.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'todo_list',
                'display_name'          => 'Todo — List',
                'description'           => 'List todos from a named list (or all lists).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'todo_complete',
                'display_name'          => 'Todo — Complete',
                'description'           => 'Mark a todo item as done by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'todo_delete',
                'display_name'          => 'Todo — Delete',
                'description'           => 'Delete a todo item by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],

            // ── Shopping list ─────────────────────────────────────────────────

            [
                'name'                  => 'shopping_add',
                'display_name'          => 'Shopping List — Add Item',
                'description'           => 'Add an item to a shopping list with optional category and quantity.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'shopping_items',
                'display_name'          => 'Shopping List — View Items',
                'description'           => 'View items on a shopping list, optionally including bought items.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'shopping_bought',
                'display_name'          => 'Shopping List — Mark Bought',
                'description'           => 'Mark a shopping list item as bought by ID.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'shopping_clear',
                'display_name'          => 'Shopping List — Clear Bought',
                'description'           => 'Remove all bought items from a shopping list.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => false,
            ],

            // ── Messaging ─────────────────────────────────────────────────────

            [
                'name'                  => 'whatsapp_send',
                'display_name'          => 'WhatsApp — Send Message',
                'description'           => 'Send a WhatsApp message via Meta WhatsApp Business Cloud API.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => true,
                'config_keys'           => ['WHATSAPP_PHONE_NUMBER_ID', 'WHATSAPP_ACCESS_TOKEN'],
            ],

            // ── Social media ──────────────────────────────────────────────────

            [
                'name'                  => 'facebook_post',
                'display_name'          => 'Facebook — Post',
                'description'           => 'Post a message (with optional link/image) to a Facebook Page.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => true,
                'config_keys'           => ['FACEBOOK_PAGE_ID', 'FACEBOOK_PAGE_ACCESS_TOKEN'],
            ],
            [
                'name'                  => 'facebook_feed',
                'display_name'          => 'Facebook — Read Feed',
                'description'           => 'Read recent posts from a Facebook Page.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['FACEBOOK_PAGE_ID', 'FACEBOOK_PAGE_ACCESS_TOKEN'],
            ],
            [
                'name'                  => 'instagram_post',
                'display_name'          => 'Instagram — Post Image',
                'description'           => 'Publish an image with caption to Instagram Business account.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'moderate',
                'requires_confirmation' => true,
                'config_keys'           => ['INSTAGRAM_BUSINESS_ACCOUNT_ID', 'FACEBOOK_PAGE_ACCESS_TOKEN'],
            ],

            // ── Document generation ───────────────────────────────────────────

            [
                'name'                  => 'generate_qr',
                'display_name'          => 'QR Code Generator',
                'description'           => 'Generate a QR code image (via qrserver.com, no API key needed).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'generate_pdf',
                'display_name'          => 'PDF Generator',
                'description'           => 'Generate a PDF from HTML content (requires barryvdh/laravel-dompdf).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'generate_docx',
                'display_name'          => 'Word Document Generator',
                'description'           => 'Generate a .docx Word document (requires phpoffice/phpword).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
            [
                'name'                  => 'generate_xlsx',
                'display_name'          => 'Excel Spreadsheet Generator',
                'description'           => 'Generate a .xlsx Excel spreadsheet (requires phpoffice/phpspreadsheet).',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],

            // ── Vision / Image ────────────────────────────────────────────────

            [
                'name'                  => 'analyze_image',
                'display_name'          => 'Image Analyzer (GPT-4o Vision)',
                'description'           => 'Analyze or describe an image using GPT-4o vision. Accepts a local file path or public URL.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['OPENAI_API_KEY'],
            ],
            [
                'name'                  => 'generate_image',
                'display_name'          => 'Image Generator (DALL-E 3)',
                'description'           => 'Generate an image with DALL-E 3. Returns the public image URL.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['OPENAI_API_KEY'],
            ],
            [
                'name'                  => 'send_telegram_image',
                'display_name'          => 'Send Telegram Image',
                'description'           => 'Send an image (URL or local path) to the Telegram user.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],

            // ── Audio ─────────────────────────────────────────────────────────

            [
                'name'                  => 'transcribe_audio',
                'display_name'          => 'Audio Transcription (Whisper)',
                'description'           => 'Transcribe an audio file to text using OpenAI Whisper.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['OPENAI_API_KEY'],
            ],
            [
                'name'                  => 'generate_audio',
                'display_name'          => 'Text-to-Speech (OpenAI TTS)',
                'description'           => 'Generate speech from text using OpenAI TTS. Returns local path to the generated MP3.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
                'config_keys'           => ['OPENAI_API_KEY'],
            ],
            [
                'name'                  => 'send_telegram_voice',
                'display_name'          => 'Send Telegram Voice/Audio',
                'description'           => 'Send an audio file as a voice or audio message to the Telegram user.',
                'type'                  => 'builtin',
                'handler_class'         => null,
                'risk_level'            => 'safe',
                'requires_confirmation' => false,
            ],
        ];

        foreach ($tools as $tool) {
            Tool::updateOrCreate(
                ['name' => $tool['name']],
                $tool
            );
        }
    }
}
